UPDATE plans 
SET coverage = '[
  "Engine",
  "Manual Gearbox", 
  "Automatic Transmission",
  "Torque Converter",
  "Overdrive",
  "Differential",
  "Electrics",
  "Casings",
  "Recovery",
  "Clutch",
  "Cooling System",
  "Fuel System",
  "Braking System",
  "Propshaft",
  "Vehicle Hire",
  "European Cover",
  "Gold plan plus:",
  "Labour up to £100 p/hr",
  "*Free Halfords MOT test",
  "*Unlimited Claims",
  "Turbo",
  "Airconditioning",
  "ECU",
  "Drive Shafts",
  "Steering",
  "Suspension",
  "Bearings",
  "Ventilation",
  "Locks",
  "Seals"
]'::jsonb,
updated_at = now()
WHERE name = 'Platinum';