-- Add personal and address details columns to customers table
ALTER TABLE customers 
ADD COLUMN phone text,
ADD COLUMN first_name text,
ADD COLUMN last_name text,
ADD COLUMN flat_number text,
ADD COLUMN building_name text,
ADD COLUMN building_number text,
ADD COLUMN street text,
ADD COLUMN town text,
ADD COLUMN county text,
ADD COLUMN postcode text,
ADD COLUMN country text DEFAULT 'United Kingdom',
ADD COLUMN vehicle_make text,
ADD COLUMN vehicle_model text,
ADD COLUMN vehicle_year text,
ADD COLUMN vehicle_fuel_type text,
ADD COLUMN vehicle_transmission text,
ADD COLUMN mileage text,
ADD COLUMN payment_type text,
ADD COLUMN stripe_session_id text,
ADD COLUMN bumper_order_id text,
ADD COLUMN discount_code text,
ADD COLUMN discount_amount numeric DEFAULT 0,
ADD COLUMN original_amount numeric,
ADD COLUMN final_amount numeric;